version: '3.3'
services:
  task-manager-frontend:
    container_name: task-manager-frontend
    image: task-manager-frontend-image
    restart: unless-stopped
    build: TaskManagerFrontend/.
    ports:
      - 80:80
    networks:
      - task-manager-network

  task-manager-backend:
    container_name: task-manager-backend
    image: task-manager-backend-image
    restart: unless-stopped
    build: TaskManagerBackend/.
    ports:
      - ${APP_PORT}:8030
    env_file:
      - .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      APP_PORT: ${APP_PORT} 
    networks:
      - task-manager-network
    depends_on:
      - task-manager-postgres

  task-manager-postgres:
    container_name: task-manager-postgres
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge