version: '3.3'
services:
  # task-manager:
  #   container_name: task-manager
  #   image: task-manager-image
  #   restart: unless-stopped
  #   build: .
  #   ports:
  #     - ${TASK_MANAGER_PORT}:8030
  #   env_file:
  #     - .env
  #   environment:
  #     DB_USERNAME: ${POSTGRES_USER}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     DATABASE: ${POSTGRES_DATABASE}
  #     DB_URL: ${DB_URL}
  #     DB_PORT: ${DB_PORT}
  #   networks:
  #     - task-manager-network
  #   depends_on:
  #     - task-manager-postgres

  task-manager-postgres:
    container_name: task-manager-postgres
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge